version: '3.8'
services:
  db:
    image: postgres:16  # Kita pakai PostgreSQL versi 16
    container_name: safevault_db
    restart: always
    ports:
      - "5432:5432"     # Pintu akses: Port Laptop -> Port Docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ;.,lpokm  # Password database (bebas)
      POSTGRES_DB: safevault       # Nama database otomatis dibuat
    volumes:
      - postgres_data:/var/lib/postgresql/data # Agar data tidak hilang saat docker dimatikan

volumes:
  postgres_data: